# Generated by Django 2.0.5 on 2018-07-11 19:25

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, upload_to='Avatar')),
                ('firstname', models.CharField(blank=True, max_length=500)),
                ('lastname', models.CharField(blank=True, max_length=500, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=500, null=True)),
                ('section', models.CharField(blank=True, max_length=500, null=True)),
                ('level', models.CharField(blank=True, max_length=500, null=True)),
                ('details', models.TextField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='cherche_s1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_cherche_s1', models.CharField(max_length=200)),
                ('sub_title_cherche_s1', models.CharField(max_length=400)),
                ('file_s1', models.FileField(blank=True, null=True, upload_to='Search_Master1')),
            ],
        ),
        migrations.CreateModel(
            name='comment_put',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=5600)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('avatar_commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.author')),
                ('user_comment', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('sub_title', models.CharField(max_length=400)),
                ('file', models.FileField(blank=True, null=True, upload_to='Cours_Master1')),
            ],
        ),
        migrations.CreateModel(
            name='Module_master2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('sub_title', models.CharField(max_length=400)),
                ('file1', models.FileField(blank=True, null=True, upload_to='Cours_Master2')),
            ],
        ),
        migrations.CreateModel(
            name='publishe_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='Attachment')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('auther', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('avatar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.author')),
            ],
        ),
        migrations.CreateModel(
            name='search_master2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_cherche_s1', models.CharField(max_length=200)),
                ('sub_title_cherche_s1', models.CharField(max_length=400)),
                ('file_s1', models.FileField(blank=True, null=True, upload_to='Search_Master2')),
            ],
        ),
        migrations.CreateModel(
            name='usercomment_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=500)),
                ('comment', models.TextField(max_length=5500, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='comment_put',
            name='user_put',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.publishe_db'),
        ),
    ]
